pipelines:
    branches:
        main:
            - step:
                  name: DOCKER BUILD
                  script:
                      - IMAGE_NAME=$BITBUCKET_REPO_SLUG
                      - docker build . --file Dockerfile --tag ${IMAGE_NAME}
                      - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
                  services:
                      - docker
                  caches:
                      - docker
                  artifacts:
                      - '*.tar'
            - step:
                  name: DOCKER PUSH
                  deployment: Production
                  script:
                      - IMAGE_NAME=$BITBUCKET_REPO_SLUG
                      - DOCKER_USERNAME='robot$harbor_api'
                      - DOCKER_PASSWORD='dzVqX0rONdfSSoVd88k8Z2Qc5CN2QHka'
                      - echo ${DOCKER_PASSWORD} | docker login harbor-dev.jinhaksa.com/jinhak_dev_repo --username='robot$harbor_api' --password-stdin
                      - docker load --input "${IMAGE_NAME}.tar"
                      - IMAGE=${IMAGE_NAME}
                      - docker tag "${IMAGE_NAME}:latest" harbor-dev.jinhaksa.com/jinhak_dev_repo/"${IMAGE_NAME}:latest"
                      - docker push harbor-dev.jinhaksa.com/jinhak_dev_repo/"${IMAGE_NAME}:latest"
                  services:
                      - docker
